# Generated by Django 4.2.7 on 2025-10-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_default_users'),
        ('accounts', '0002_twofactorauth_passwordhistory_loginattempt_and_more'),
    ]

    operations = [
    ]
