# Generated by Django 4.2.7 on 2025-10-16 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_verification', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='documents.documentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(help_text='Unique document number', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/student_docs/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('archived', 'Archived')], default='available', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('claimed_by_name', models.CharField(blank=True, help_text='Name of person who claimed', max_length=200)),
                ('claimed_by_relation', models.CharField(blank=True, help_text='Relationship to student', max_length=50)),
                ('claimed_by_id_number', models.CharField(blank=True, help_text='ID number of claimant', max_length=50)),
                ('claim_remarks', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created', 'student__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by_name', models.CharField(max_length=200)),
                ('claimed_by_relation', models.CharField(max_length=50)),
                ('claimed_by_id_number', models.CharField(max_length=50)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_claims', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='documents.studentdocument')),
            ],
            options={
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('excel_file', models.FileField(upload_to='documents/batches/')),
                ('total_documents', models.IntegerField(default=0)),
                ('imported_documents', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['status'], name='documents_s_status_3bee8b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['document_type'], name='documents_s_documen_c04c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['date_created'], name='documents_s_date_cr_a4cb17_idx'),
        ),
    ]
