# Generated by Django 4.2.7 on 2025-10-16 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF10Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g., 2023-2024', max_length=20)),
                ('grade_level', models.CharField(help_text='e.g., Grade 12', max_length=10)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('lrn', models.CharField(help_text='Learner Reference Number', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_contact', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_contact', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_contact', models.CharField(blank=True, max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_grade', models.CharField(blank=True, max_length=20)),
                ('date_of_enrollment', models.DateField()),
                ('date_of_graduation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('transferred', 'Transferred'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='sf10/excel/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='sf10/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sf10', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf10_records', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='SF10Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('excel_file', models.FileField(upload_to='sf10/uploads/')),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SF10Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('first_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('third_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fourth_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('sf10_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='documents.sf10document')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='SF10Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_tardy', models.IntegerField(default=0)),
                ('sf10_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='documents.sf10document')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
